# Copyright 2015-2016 Harri Kapanen <harri.kapanen@iki.fi>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# Run setup first, then
# export ANSIBLE_VAULT_PASSWORD_FILE=<file>
# ./provision.sh 192.168.1.100 playbooks/tkurki/cassiopeia.yml

- hosts: all
  remote_user: pi
  gather_facts: yes
  become: yes

  vars:
    - hostname: cassiopeia
    - timezone: Europe/Helsinki

  vars_files:
    - secrets.yml

  roles:
    - common
    - role: huawei_e3372h
    - role: upnpc
      upnpc_interface: eth1
      upnpc_port_forwards: "500 UDP 4500 UDP 1701 UDP"
      upnpc_port_redirects:
        - "192.168.8.100 22 2222 tcp"
    - hotspot
    - role: nat_router
      nat_router_fw_input_rules:
        - "-A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT"
        - "-A FORWARD -i wlan0 -o eth0 -j ACCEPT"
    - aws-cli
    - signalk-docker
    - zerotier

  handlers:
    - include: ../../handlers/handlers.yml
