---
- name: Enable RTC
  lineinfile:
    dest: /boot/config.txt
    line: 'dtoverlay=i2c-rtc,ds3231'
    state: present
  notify: reboot

- name: Setup udev rule to update system time from RTC
  copy:
    src: 85-hwclock.rules
    dest: /etc/udev/rules.d/85-hwclock.rules
