#
# Example plugin installation:
# - role: signalk
#   signalk_plugins:
#     - plugin_name: "@signalk/aisreporter"
#       plugin_config_src: signalk-aisreporter-conf.json
#       plugin_config_dst: aisreporter.json

---
- name: "Install SignalK server plugin: {{ plugin_name }}"
  npm:
    name: "{{ plugin_name }}"
    path: "/home/{{ signalk_user }}/.signalk/"
    production: yes
  async: 3600
  poll: 10
  become_user: "{{ signalk_user }}"
  when: plugin_name is defined
  notify: restart-signalk-server
  tags: signalk-npm

- name: "Create SignalK server plugin config directory"
  file:
    path: "/home/{{ signalk_user }}/.signalk/plugin-config-data"
    state: directory
    owner: "{{ signalk_user }}"
    group: "{{ signalk_user }}"
  when: plugin_config_src != "" and plugin_config_dst != ""
  tags: signalk-npm

- name: "Install SignalK server plugin config: {{ plugin_name }}"
  copy:
    src: "{{ plugin_config_src }}"
    dest: "/home/{{ signalk_user }}/.signalk/plugin-config-data/{{ plugin_config_dst }}"
    mode: 0644
  become_user: "{{ signalk_user }}"
  when: plugin_config_src != "" and plugin_config_dst != ""
  notify: restart-signalk-server
  tags: signalk-npm
