---
- name: Install PGP key for Zerotier repository
  apt_key: url=https://download.zerotier.com/contact@zerotier.com.gpg state=present

- name: Add Zerotier repository
  apt_repository:
    repo: "deb http://download.zerotier.com/debian/{{ ansible_distribution_release }} {{ ansible_distribution_release }} main"
    state: present

- name: Install zerotier-one
  apt: pkg=zerotier-one state=latest

- name: List joined networks
  shell: zerotier-cli listnetworks | grep {{zerotier_network_id}}
  register: zerotier_network
  failed_when: zerotier_network.rc > 1
  changed_when: False

- name: Join Zerotier network
  shell: zerotier-cli join {{zerotier_network_id}}
  when: zerotier_network.stdout == ""

- name: Check zerotier moon
  shell: zerotier-cli listpeers | grep {{zerotier_moon_id}}
  register: zerotier_moon
  failed_when: zerotier_moon.rc > 1
  when: zerotier_moon_id is defined
  changed_when: False

- name: Orbit Zerotier moon
  shell: zerotier-cli orbit {{zerotier_moon_id}} {{zerotier_moon_id}}
  when: zerotier_moon_id is defined and zerotier_moon.stdout == ""
